# https://github.com/googleapis/repo-automation-bots/tree/main/packages/sync-repo-settings
# Rules for main branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `main`
- pattern: main
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'OwlBot Post Processor'
    - 'docs'
    - 'docfx'
    - 'lint'
    - 'unit (3.7)'
    - 'unit (3.8)'
    - 'unit (3.9)'
    - 'unit (3.10)'
    - 'cover'
    - 'Samples - Lint'
    - 'Samples - Python 3.7'
    - 'Samples - Python 3.8'
    - 'Samples - Python 3.9'
    - 'Samples - Python 3.10'
