# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.cloud.dialogflow_v2beta1.proto import tier_pb2 as google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2


class TiersStub(object):
  """# Manages agent tier.

  Standard methods.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAgentTier = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Tiers/GetAgentTier',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.GetAgentTierRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.AgentTier.FromString,
        )
    self.UpdateAgentTier = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Tiers/UpdateAgentTier',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.UpdateAgentTierRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.AgentTier.FromString,
        )


class TiersServicer(object):
  """# Manages agent tier.

  Standard methods.
  """

  def GetAgentTier(self, request, context):
    """Retrieves the tier of the specified agent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAgentTier(self, request, context):
    """Updates the tier of the specified agent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TiersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAgentTier': grpc.unary_unary_rpc_method_handler(
          servicer.GetAgentTier,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.GetAgentTierRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.AgentTier.SerializeToString,
      ),
      'UpdateAgentTier': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAgentTier,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.UpdateAgentTierRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_tier__pb2.AgentTier.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.dialogflow.v2beta1.Tiers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
