# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dialogflow_v2beta1.proto import runtime_pb2 as google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class RuntimesStub(object):
  """Manages agent runtimes.


  Standard methods.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListRuntimes = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/ListRuntimes',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.ListRuntimesRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.ListRuntimesResponse.FromString,
        )
    self.GetRuntime = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/GetRuntime',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.GetRuntimeRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.Runtime.FromString,
        )
    self.CreateRuntime = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/CreateRuntime',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.CreateRuntimeRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.Runtime.FromString,
        )
    self.UpdateRuntime = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/UpdateRuntime',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.UpdateRuntimeRequest.SerializeToString,
        response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
        )
    self.DeleteRuntime = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/DeleteRuntime',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.DeleteRuntimeRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetRuntimeHistory = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Runtimes/GetRuntimeHistory',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.GetRuntimeHistoryRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.RuntimeHistory.FromString,
        )


class RuntimesServicer(object):
  """Manages agent runtimes.


  Standard methods.
  """

  def ListRuntimes(self, request, context):
    """Returns the list of all runtimes of the specified agent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRuntime(self, request, context):
    """Retrieves the specified agent runtime.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateRuntime(self, request, context):
    """Creates an agent runtime.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRuntime(self, request, context):
    """Updates the specified agent runtime.

    This method allows you to deploy new agent versions into the runtime.
    When a runtime is pointed to a new agent version by setting
    `runtime.agent_version`, the runtime is temporarily set to the `LOADING`
    state. During that time, the runtime keeps on serving the previous version
    of the agent. After the new agent version is done loading, the runtime is
    set back to the `RUNNING` state.

    Operation<response: Runtime>
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRuntime(self, request, context):
    """Deletes the specified agent runtime.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRuntimeHistory(self, request, context):
    """Gets the history of the specified runtime.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RuntimesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListRuntimes': grpc.unary_unary_rpc_method_handler(
          servicer.ListRuntimes,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.ListRuntimesRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.ListRuntimesResponse.SerializeToString,
      ),
      'GetRuntime': grpc.unary_unary_rpc_method_handler(
          servicer.GetRuntime,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.GetRuntimeRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.Runtime.SerializeToString,
      ),
      'CreateRuntime': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRuntime,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.CreateRuntimeRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.Runtime.SerializeToString,
      ),
      'UpdateRuntime': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateRuntime,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.UpdateRuntimeRequest.FromString,
          response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
      ),
      'DeleteRuntime': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRuntime,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.DeleteRuntimeRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetRuntimeHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetRuntimeHistory,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.GetRuntimeHistoryRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_runtime__pb2.RuntimeHistory.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.dialogflow.v2beta1.Runtimes', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
