# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dialogflow_v2beta1.proto import version_pb2 as google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class VersionsStub(object):
  """Manages agent versions.


  Standard methods.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListVersions = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Versions/ListVersions',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.ListVersionsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.ListVersionsResponse.FromString,
        )
    self.GetVersion = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Versions/GetVersion',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.GetVersionRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.FromString,
        )
    self.CreateVersion = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Versions/CreateVersion',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.CreateVersionRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.FromString,
        )
    self.UpdateVersion = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Versions/UpdateVersion',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.UpdateVersionRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.FromString,
        )
    self.DeleteVersion = channel.unary_unary(
        '/google.cloud.dialogflow.v2beta1.Versions/DeleteVersion',
        request_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.DeleteVersionRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class VersionsServicer(object):
  """Manages agent versions.


  Standard methods.
  """

  def ListVersions(self, request, context):
    """Returns the list of all versions of the specified agent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVersion(self, request, context):
    """Retrieves the specified agent version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateVersion(self, request, context):
    """Creates an agent version.

    The new version points to the agent instance in the "default" runtime.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateVersion(self, request, context):
    """Updates the specified agent version.

    Note that this method does not allow you to update the state of the agent
    the given version points to. It allows you to update only mutable
    properties of the version resource.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVersion(self, request, context):
    """Deletes the specified agent version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VersionsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListVersions': grpc.unary_unary_rpc_method_handler(
          servicer.ListVersions,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.ListVersionsRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.ListVersionsResponse.SerializeToString,
      ),
      'GetVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetVersion,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.GetVersionRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.SerializeToString,
      ),
      'CreateVersion': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVersion,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.CreateVersionRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.SerializeToString,
      ),
      'UpdateVersion': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateVersion,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.UpdateVersionRequest.FromString,
          response_serializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.Version.SerializeToString,
      ),
      'DeleteVersion': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVersion,
          request_deserializer=google_dot_cloud_dot_dialogflow__v2beta1_dot_proto_dot_version__pb2.DeleteVersionRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.dialogflow.v2beta1.Versions', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
